version: "3.9"
services:
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST="redis:6379"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.4'
          memory: 400M
  redis:
    image: "redislabs/rejson:2.4.2"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.4'
          memory: 400M
volumes:
  redis_data: {}